apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aad-pod-identity
  namespace: kube-system
spec:
  releaseName: aad-pod-identity
  chart:
    spec:
      chart: aad-pod-identity
      version: "4.1.6"
      sourceRef:
        kind: HelmRepository
        name: aad-pod-identity
        namespace: flux-system
  interval: 30s
  install:
    remediation:
      retries: 3