apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-secrets-store-provider-azure
  namespace: kube-system
spec:
  releaseName: csi-secrets-store-provider-azure
  chart:
    spec:
      chart: csi-secrets-store-provider-azure
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: csi-secrets-store-provider-azure
        namespace: flux-system
  interval: 30s
  install:
    remediation:
      retries: 3
  values:
    secrets-store-csi-driver:
      enableSecretRotation: true